# Generated by Django 3.2.8 on 2021-10-13 09:42

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_no',
            field=models.IntegerField(default=0, validators=[event.models.student.validate_moibil_no]),
        ),
    ]
